"""
HoneySSH — server entry point.

Starts the Twisted SSH (and optionally Telnet) honeypot using Cowrie's
infrastructure with our LLM-backed protocol handlers.

Usage:
    python start.py                  # reads .env for config
    HONEYPOT_SSH_PORT=2222 python start.py

Docker:
    The docker/entrypoint.sh waits for Ollama then calls this script.
"""

from __future__ import annotations

import os
import sys
import time
import uuid

# Load .env before anything that reads env vars
from dotenv import load_dotenv
load_dotenv()

# ── Twisted / Cowrie setup ────────────────────────────────────────────────
from twisted.internet import reactor, endpoints
from twisted.python import log
from twisted.conch.ssh import factory as ssh_factory, keys, transport as ssh_transport
from twisted.cred import portal as cred_portal
from twisted.conch.interfaces import IConchUser
from zope.interface import implementer

# ── Our transport (FrontendSSHTransport extends SSHServerTransport) ────────
from server.ssh.server_transport import FrontendSSHTransport
from server.protocols.ssh import SSH


# ── Minimal Twisted Cred realm ─────────────────────────────────────────────
# Actual channel/shell handling is done by server/protocols/ssh.py (sshParse),
# so this avatar only needs to satisfy the IConchUser interface contract.

@implementer(IConchUser)
class _HoneypotAvatar:
    conn = None

    def __init__(self, username: bytes):
        self.username = username

    def lookupChannel(self, channelType, windowSize, maxPacket, data):
        raise NotImplementedError("channels handled by sshParse")

    def lookupSubsystem(self, subsystem, data):
        return None

    def gotGlobalRequest(self, requestType, data):
        return False


class _HoneypotRealm:
    def requestAvatar(self, avatarId, mind, *interfaces):
        if IConchUser in interfaces:
            return IConchUser, _HoneypotAvatar(avatarId), lambda: None
        raise NotImplementedError("No supported interfaces")


class StandaloneFrontendSSHTransport(FrontendSSHTransport):
    """
    Variant of FrontendSSHTransport that needs no real backend SSH server.

    connectionMade() in the base class reads [proxy] backend_ssh_host from
    cowrie.cfg and calls connect_to_backend().  We override connect_to_backend
    to skip the real TCP dial and immediately mark the backend as connected,
    so the attacker's session continues straight to the LLM.
    """

    def connect_to_backend(self, ip: str, port: int) -> None:
        """Skip real TCP dial — LLM is the backend."""
        self.backend_ip = ip
        self.backend_port = port
        # Replace Cowrie's proxy SSH parser with our standalone version.
        # The base class connectionMade() already created sshParse using
        # Cowrie's proxy SSH, which requires a real backend client.
        # Our server/protocols/ssh.SSH handles channels without one.
        self.sshParse = SSH(self)
        self.backendConnected = True
        self.startTime = time.time()
        log.msg(
            eventid="cowrie.proxy.backend_connected",
            format="LLM backend ready (standalone mode)",
            session=self.transportId,
            sessionno=self.sessionno,
            protocol="ssh",
        )
        self.setTimeout(600)  # 10-minute idle timeout; LLM can be slow

# ── Cowrie config shim ─────────────────────────────────────────────────────
#    CowrieConfig.read() looks for cowrie.cfg in the working directory
#    or the path set in COWRIE_HONEYPOT_DATA_PATH.  We point it at etc/.
os.environ.setdefault("COWRIE_HONEYPOT_DATA_PATH", os.path.join(os.getcwd(), "etc"))

import logging
logging.basicConfig(
    stream=sys.stdout,
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log.startLogging(sys.stdout, setStdout=False)

# ── Configuration ─────────────────────────────────────────────────────────
SSH_PORT    = int(os.getenv("HONEYPOT_SSH_PORT",    "2222"))
TELNET_PORT = int(os.getenv("HONEYPOT_TELNET_PORT", "2223"))
KEY_DIR     = os.path.join(os.getcwd(), "etc")


class HoneySSHFactory(ssh_factory.SSHFactory):
    """
    Twisted SSHFactory that creates FrontendSSHTransport instances.

    SSHFactory needs:
      - publicKeys  : dict mapping algorithm name → twisted.conch.ssh.keys.Key
      - privateKeys : same, but private half
      - services    : dict mapping service name → service class
    """

    protocol = StandaloneFrontendSSHTransport

    def __init__(self):
        # Load host keys generated by the Dockerfile (or keygen locally)
        rsa_priv = os.path.join(KEY_DIR, "ssh_host_rsa_key")
        rsa_pub  = os.path.join(KEY_DIR, "ssh_host_rsa_key.pub")

        if not os.path.exists(rsa_priv):
            _generate_host_keys(KEY_DIR)

        # Twisted looks up keys by bytes algorithm name (e.g. b"ssh-rsa")
        self.publicKeys  = {b"ssh-rsa": keys.Key.fromFile(rsa_pub)}
        self.privateKeys = {b"ssh-rsa": keys.Key.fromFile(rsa_priv)}

        # ed25519 is preferred by modern SSH clients — add it if the key exists
        ed_priv = os.path.join(KEY_DIR, "ssh_host_ed25519_key")
        ed_pub  = os.path.join(KEY_DIR, "ssh_host_ed25519_key.pub")
        if os.path.exists(ed_priv):
            self.publicKeys[b"ssh-ed25519"]  = keys.Key.fromFile(ed_pub)
            self.privateKeys[b"ssh-ed25519"] = keys.Key.fromFile(ed_priv)

        # Cowrie's userauth + connection services
        from cowrie.ssh.userauth import HoneyPotSSHUserAuthServer
        from cowrie.ssh.connection import CowrieSSHConnection
        from cowrie.core.checkers import HoneypotPasswordChecker, HoneypotNoneChecker
        self.services = {
            b"ssh-userauth": HoneyPotSSHUserAuthServer,
            b"ssh-connection": CowrieSSHConnection,
        }

        # Portal: HoneypotPasswordChecker reads auth_class from cowrie.cfg
        # HoneypotNoneChecker handles "none" auth method
        self.portal = cred_portal.Portal(_HoneypotRealm())
        self.portal.registerChecker(HoneypotPasswordChecker())
        self.portal.registerChecker(HoneypotNoneChecker())


def _generate_host_keys(key_dir: str) -> None:
    """Generate RSA and Ed25519 host keys on first run (local / dev mode)."""
    import subprocess
    os.makedirs(key_dir, exist_ok=True)
    for key_type, key_file in [
        ("rsa",     os.path.join(key_dir, "ssh_host_rsa_key")),
        ("ed25519", os.path.join(key_dir, "ssh_host_ed25519_key")),
    ]:
        if not os.path.exists(key_file):
            log.msg(f"Generating {key_type} host key → {key_file}")
            subprocess.run(
                ["ssh-keygen", "-t", key_type, "-f", key_file, "-N", ""],
                check=True, capture_output=True,
            )


def main() -> None:
    log.msg("=" * 60)
    log.msg("  HoneySSH starting")
    log.msg(f"  SSH    port : {SSH_PORT}")
    log.msg(f"  Telnet port : {TELNET_PORT}")
    log.msg(f"  Ollama      : {os.getenv('OLLAMA_URL', 'http://localhost:11434')}")
    log.msg(f"  Model       : {os.getenv('OLLAMA_MODEL', 'llama3.2')}")
    log.msg("=" * 60)

    factory = HoneySSHFactory()

    ssh_endpoint = endpoints.TCP4ServerEndpoint(reactor, SSH_PORT)
    ssh_endpoint.listen(factory)
    log.msg(f"SSH honeypot listening on port {SSH_PORT}")

    # ── Telnet (optional) ─────────────────────────────────────────────────
    try:
        from server.telnet.handler import TelnetHandler
        from twisted.internet.protocol import ServerFactory as TelnetFactory

        class _TelnetFactory(TelnetFactory):
            protocol = TelnetHandler

        telnet_endpoint = endpoints.TCP4ServerEndpoint(reactor, TELNET_PORT)
        telnet_endpoint.listen(_TelnetFactory())
        log.msg(f"Telnet honeypot listening on port {TELNET_PORT}")
    except Exception as exc:
        log.msg(f"Telnet not started: {exc}")

    reactor.run()


if __name__ == "__main__":
    main()
