"""
HoneySSH — server entry point.

Starts the Twisted SSH (and optionally Telnet) honeypot using Cowrie's
infrastructure with our LLM-backed protocol handlers.

Usage:
    python start.py                  # reads .env for config
    HONEYPOT_SSH_PORT=2222 python start.py

Docker:
    The docker/entrypoint.sh waits for Ollama then calls this script.
"""

from __future__ import annotations

import os
import sys

# Load .env before anything that reads env vars
from dotenv import load_dotenv
load_dotenv()

# ── Twisted / Cowrie setup ────────────────────────────────────────────────
from twisted.internet import reactor, endpoints
from twisted.python import log
from twisted.conch.ssh import factory as ssh_factory, keys

# ── Our transport (FrontendSSHTransport extends SSHServerTransport) ────────
from server.ssh.server_transport import FrontendSSHTransport

# ── Cowrie config shim ─────────────────────────────────────────────────────
#    CowrieConfig.read() looks for cowrie.cfg in the working directory
#    or the path set in COWRIE_HONEYPOT_DATA_PATH.  We point it at etc/.
os.environ.setdefault("COWRIE_HONEYPOT_DATA_PATH", os.path.join(os.getcwd(), "etc"))

import logging
logging.basicConfig(
    stream=sys.stdout,
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log.startLogging(sys.stdout, setStdout=False)

# ── Configuration ─────────────────────────────────────────────────────────
SSH_PORT    = int(os.getenv("HONEYPOT_SSH_PORT",    "2222"))
TELNET_PORT = int(os.getenv("HONEYPOT_TELNET_PORT", "2223"))
KEY_DIR     = os.path.join(os.getcwd(), "etc")


class HoneySSHFactory(ssh_factory.SSHFactory):
    """
    Twisted SSHFactory that creates FrontendSSHTransport instances.

    SSHFactory needs:
      - publicKeys  : dict mapping algorithm name → twisted.conch.ssh.keys.Key
      - privateKeys : same, but private half
      - services    : dict mapping service name → service class
    """

    protocol = FrontendSSHTransport

    def __init__(self):
        # Load host keys generated by the Dockerfile (or keygen locally)
        rsa_priv = os.path.join(KEY_DIR, "ssh_host_rsa_key")
        rsa_pub  = os.path.join(KEY_DIR, "ssh_host_rsa_key.pub")

        if not os.path.exists(rsa_priv):
            _generate_host_keys(KEY_DIR)

        self.publicKeys  = {"ssh-rsa": keys.Key.fromFile(rsa_pub)}
        self.privateKeys = {"ssh-rsa": keys.Key.fromFile(rsa_priv)}

        # Try to also load ed25519 if present (preferred by modern clients)
        ed_priv = os.path.join(KEY_DIR, "ssh_host_ed25519_key")
        ed_pub  = os.path.join(KEY_DIR, "ssh_host_ed25519_key.pub")
        if os.path.exists(ed_priv):
            self.publicKeys["ssh-ed25519"]  = keys.Key.fromFile(ed_pub)
            self.privateKeys["ssh-ed25519"] = keys.Key.fromFile(ed_priv)

        # Cowrie's userauth + connection services
        from cowrie.ssh.userauth import HoneypotSSHUserAuthServer
        from cowrie.ssh.connection import CowrieSSHConnection
        self.services = {
            b"ssh-userauth": HoneypotSSHUserAuthServer,
            b"ssh-connection": CowrieSSHConnection,
        }


def _generate_host_keys(key_dir: str) -> None:
    """Generate RSA and Ed25519 host keys on first run (local / dev mode)."""
    import subprocess
    os.makedirs(key_dir, exist_ok=True)
    for key_type, key_file in [
        ("rsa",     os.path.join(key_dir, "ssh_host_rsa_key")),
        ("ed25519", os.path.join(key_dir, "ssh_host_ed25519_key")),
    ]:
        if not os.path.exists(key_file):
            log.msg(f"Generating {key_type} host key → {key_file}")
            subprocess.run(
                ["ssh-keygen", "-t", key_type, "-f", key_file, "-N", ""],
                check=True, capture_output=True,
            )


def main() -> None:
    log.msg("=" * 60)
    log.msg("  HoneySSH starting")
    log.msg(f"  SSH    port : {SSH_PORT}")
    log.msg(f"  Telnet port : {TELNET_PORT}")
    log.msg(f"  Ollama      : {os.getenv('OLLAMA_URL', 'http://localhost:11434')}")
    log.msg(f"  Model       : {os.getenv('OLLAMA_MODEL', 'llama3.2')}")
    log.msg("=" * 60)

    factory = HoneySSHFactory()

    ssh_endpoint = endpoints.TCP4ServerEndpoint(reactor, SSH_PORT)
    ssh_endpoint.listen(factory)
    log.msg(f"SSH honeypot listening on port {SSH_PORT}")

    # ── Telnet (optional) ─────────────────────────────────────────────────
    try:
        from server.telnet.handler import TelnetHandler
        from twisted.internet.protocol import ServerFactory as TelnetFactory

        class _TelnetFactory(TelnetFactory):
            protocol = TelnetHandler

        telnet_endpoint = endpoints.TCP4ServerEndpoint(reactor, TELNET_PORT)
        telnet_endpoint.listen(_TelnetFactory())
        log.msg(f"Telnet honeypot listening on port {TELNET_PORT}")
    except Exception as exc:
        log.msg(f"Telnet not started: {exc}")

    reactor.run()


if __name__ == "__main__":
    main()
